version: "3.9"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/python
    # This is where ports would go
    networks:
      - python-network
  # Additional services here
# volumes here
networks:
  python-network:
    driver: bridge
    